project:
  type: website

execute:
  freeze: auto


website:
  title: "IABEM"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - organization.qmd
      - href: symposium.qmd
        text: Symposium

format:
  html:
    theme: flatly
    css: styles.css
    toc: false



